name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: repository
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_presets: "@ocean-blue"
          user: Tartiine
          repo: metrics
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_stars: yes
          plugin_stars_limit: 1
          plugin_people: yes
          plugin_people_limit: 10
          plugin_people_size: 60
          plugin_people_types: followers, following, thanks
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_limit: 10
